name: Send Daily Messages

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  cron_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run task
        run: |
          curl -X POST ${{ secrets.EDGE_FUNCTION_SEND_DAY_MESSAGES_URL }}
